### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by micknudsen** [micknudsen/QCI-Tools#1]
The command line interface is rather clumsy. Would be great to have something like `qcitools COMMAND OPTIONS`, where `qcitools COMMAND --help` would show only OPTIONS relevant for COMMAND. Maybe the [Click](http://click.pocoo.org/5/) package can do that?

**Comment by dansondergaard** [comment]
Yes.

**Comment by micknudsen** [comment]
Just what I thought. Tried sampling bits and pieces from the documentation without any success. Guess I will have to sit down and read the documentation from the beginning ... and figure out exactly what decorators are.

**Comment by dansondergaard** [comment]
Knowing decorators is very beneficial indeed ;)
